name: "lint"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint codebase
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - run: go mod download
      - run: go vet ./...
      - run: make lint-prepare
      - run: ./bin/golangci-lint run
